spring:
  flyway:
    enabled: true
    locations: classpath:db/migration/general,classpath:db/migration/{vendor},classpath:db/test/migration

  h2:
    console:
      enabled: true
  jpa:
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

server:
  shutdown: immediate