spring:
  flyway:
    locations: classpath:db/migration/general,classpath:db/migration/postgres,classpath:db/test/migration

  h2:
    console:
      enabled: true
  jpa:
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

server:
  shutdown: immediate

oauth:
  endpoint.url: http://localhost:8080/auth

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0
