spring:
  application:
    name: probation-teams

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
            
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration/general,classpath:db/migration/{vendor}
    schemas: probation_teams
    url: 'jdbc:h2:mem:probation-teams-db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1'
    user: 'sa'
    password: ''
    placeholders:
      database_password: dummy

  datasource:
    # This reopens the H2 database prepared by flyway with default schema and user probation_teams
    url: 'jdbc:h2:mem:probation-teams-db;MODE=PostgreSQL;SCHEMA="probation_teams";IFEXISTS=TRUE'
    continue-on-error: true
    username: probation_teams
    password: dummy

    hikari:
      pool-name: ProbationTeams-CP
      connectionTimeout: 1000
      validationTimeout:  500

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol_header: x-forwarded-proto

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info,health'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
    info:
      cache:
        time-to-live: 2000ms

graceful:
  shutdown:
    enabled: true

azure:
  application-insights:
    web:
      enable-W3C: true