INSERT INTO LOCAL_DELIVERY_UNIT(LOCAL_DELIVERY_UNIT_ID, CODE, CREATE_DATE_TIME, CREATE_USER_ID) VALUES('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'ABC124', now(), 'SYSTEM');
INSERT INTO LOCAL_DELIVERY_UNIT(LOCAL_DELIVERY_UNIT_ID, CODE, FUNCTIONAL_MAIL_BOX, CREATE_DATE_TIME, CREATE_USER_ID) VALUES('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'ABC125', 'a@b.com', now(), 'SYSTEM');

