INSERT INTO LOCAL_DELIVERY_UNIT2(LOCAL_DELIVERY_UNIT_ID, PROBATION_AREA_CODE, LOCAL_DELIVERY_UNIT_CODE, FUNCTIONAL_MAILBOX, CREATE_DATE_TIME, CREATE_USER_ID) VALUES('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'ABC', 'ABC124', 'c@d.org', now(), 'SYSTEM');
INSERT INTO LOCAL_DELIVERY_UNIT2(LOCAL_DELIVERY_UNIT_ID, PROBATION_AREA_CODE, LOCAL_DELIVERY_UNIT_CODE, FUNCTIONAL_MAILBOX, CREATE_DATE_TIME, CREATE_USER_ID) VALUES('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'ABC', 'ABC125', 'a@b.com', now(), 'SYSTEM');

