generic-service:
  nameOverride: probation-teams
  replicaCount: 4
  image:
    repository: quay.io/hmpps/probation-teams
    tag: app_version
    port: 8080
  ingress:
    enabled: true
    host: app-hostname.local
    tlsSecretName: probation-teams-cert
    path: /
    v1_2_enabled: true
    v0_47_enabled: false
  env:
    JAVA_OPTS: -Xmx512m
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: logstash
    SPRING_DATASOURCE_USERNAME: probation_teams
    APPLICATIONINSIGHTS_CONNECTION_STRING: InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
  namespace_secrets:
    probation-teams:
      APPINSIGHTS_INSTRUMENTATIONKEY: APPINSIGHTS_INSTRUMENTATIONKEY
    dps-rds-instance-output:
      SPRING_DATASOURCE_PASSWORD: probation_teams_password
      DATABASE_NAME: database_name
      DATABASE_ENDPOINT: rds_instance_endpoint
      SUPERUSER_USERNAME: database_username
      SUPERUSER_PASSWORD: database_password
  allowlist:
    groups:
      - internal
generic-prometheus-alerts:
  targetApplication: probation-teams
  alertSeverity: digital-prison-service-dev
