---
# Values here are the same across all environments

generic-service:
  nameOverride: probation-teams

  replicaCount: 4

  image:
    repository: quay.io/hmpps/probation-teams
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: probation-teams-cert
    path: /
    v1_2_enabled: true
    v0_47_enabled: true

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    SPRING_DATASOURCE_USERNAME: "probation_teams"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    probation-teams:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
    dps-rds-instance-output:
      SPRING_DATASOURCE_PASSWORD: "probation_teams_password"
      DATABASE_NAME: "database_name"
      DATABASE_ENDPOINT: "rds_instance_endpoint"
      SUPERUSER_USERNAME: "database_username"
      SUPERUSER_PASSWORD: "database_password"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"
    global-protect: "35.176.93.186/32"
    petty-france-wifi: "213.121.161.112/28"

generic-prometheus-alerts:
  targetApplication: probation-teams
  alertSeverity: digital-prison-service-dev
