---
# Per environment values which override defaults in probation-teams/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: probation-teams-dev.prison.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    OAUTH_ENDPOINT_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
