DROP INDEX IF EXISTS LOCAL_DELIVERY_UNIT_IDX1;
DROP TABLE IF EXISTS LOCAL_DELIVERY_UNIT;

CREATE TABLE LOCAL_DELIVERY_UNIT
(
    LOCAL_DELIVERY_UNIT_ID UUID         PRIMARY KEY,
    CODE                   VARCHAR(126) NOT NULL,
    FUNCTIONAL_MAILBOX     VARCHAR(126) NOT NULL,
    CREATE_DATE_TIME       TIMESTAMP    NOT NULL,
    CREATE_USER_ID         VARCHAR(32)  NOT NULL,
    MODIFY_DATE_TIME       TIMESTAMP,
    MODIFY_USER_ID         VARCHAR(32)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON LOCAL_DELIVERY_UNIT TO probation_teams;

CREATE UNIQUE INDEX LOCAL_DELIVERY_UNIT_IDX1 ON LOCAL_DELIVERY_UNIT(CODE);

COMMENT ON TABLE LOCAL_DELIVERY_UNIT                         IS 'Holds information about a Local Delivery Unit';
COMMENT ON COLUMN LOCAL_DELIVERY_UNIT.LOCAL_DELIVERY_UNIT_ID IS 'Surrogate key';
COMMENT ON COLUMN LOCAL_DELIVERY_UNIT.CODE                   IS 'Local Delivery Unit Code. Business key';
