DROP INDEX IF EXISTS LOCAL_DELIVERY_UNIT2_IDX1;
DROP TABLE IF EXISTS LOCAL_DELIVERY_UNIT2;

CREATE TABLE LOCAL_DELIVERY_UNIT2
(
    LOCAL_DELIVERY_UNIT_ID   UUID PRIMARY KEY,
    PROBATION_AREA_CODE      VARCHAR(126) NOT NULL,
    LOCAL_DELIVERY_UNIT_CODE VARCHAR(126) NOT NULL,
    FUNCTIONAL_MAILBOX       VARCHAR(126),
    CREATE_DATE_TIME         TIMESTAMP    NOT NULL,
    CREATE_USER_ID           VARCHAR(32)  NOT NULL,
    MODIFY_DATE_TIME         TIMESTAMP,
    MODIFY_USER_ID           VARCHAR(32)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON LOCAL_DELIVERY_UNIT2 TO probation_teams;

CREATE UNIQUE INDEX LOCAL_DELIVERY_UNIT2_IDX1 ON LOCAL_DELIVERY_UNIT2 (PROBATION_AREA_CODE, LOCAL_DELIVERY_UNIT_CODE);

COMMENT ON TABLE LOCAL_DELIVERY_UNIT2 IS 'Holds information about a Local Delivery Unit';
COMMENT ON COLUMN LOCAL_DELIVERY_UNIT2.LOCAL_DELIVERY_UNIT_ID IS 'Surrogate key';
COMMENT ON COLUMN LOCAL_DELIVERY_UNIT2.PROBATION_AREA_CODE IS 'Probation Area Code. First part of the business key';
COMMENT ON COLUMN LOCAL_DELIVERY_UNIT2.LOCAL_DELIVERY_UNIT_CODE IS 'Local Delivery Unit Code. Second part of the business key';
