DROP TABLE IF EXISTS PROBATION_TEAM;

CREATE TABLE PROBATION_TEAM
(
    LOCAL_DELIVERY_UNIT_ID UUID NOT NULL,
    TEAM_CODE              VARCHAR(126) NOT NULL,
    FUNCTIONAL_MAILBOX     VARCHAR(126) NOT NULL,

    CONSTRAINT PROBATION_TEAM_PK PRIMARY KEY (LOCAL_DELIVERY_UNIT_ID, TEAM_CODE),
    CONSTRAINT PROBATION_TEAM_LOCAL_DELIVERY_UNIT_FK FOREIGN KEY (LOCAL_DELIVERY_UNIT_ID) REFERENCES LOCAL_DELIVERY_UNIT2 (LOCAL_DELIVERY_UNIT_ID)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON PROBATION_TEAM TO probation_teams;

COMMENT ON TABLE PROBATION_TEAM IS 'Holds information about a probation team.  A Probation Team is in a many-to-one child-parent relationship with a LOCAL_DELIVERY_UNIT2';
COMMENT ON COLUMN PROBATION_TEAM.LOCAL_DELIVERY_UNIT_ID IS 'The surrogate key to a LOCAL_DELIVERY_UNIT2. Part of the primary key and also a foreign key.';
COMMENT ON COLUMN PROBATION_TEAM.TEAM_CODE IS 'The code for this probation team.  Forms part of the primary key';
COMMENT ON COLUMN PROBATION_TEAM.FUNCTIONAL_MAILBOX IS 'The functional mailbox for this probation team.';
