DROP INDEX IF EXISTS PROBATION_TEAM_IDX1;
DROP TABLE IF EXISTS PROBATION_TEAM;

CREATE TABLE LOCAL_DELIVERY_UNIT
(
    LOCAL_DELIVERY_UNIT_ID UUID         PRIMARY KEY,
    CODE                   VARCHAR(126) NOT NULL,
    FUNCTIONAL_MAIL_BOX    VARCHAR(126),
    CREATE_DATE_TIME       TIMESTAMP    NOT NULL,
    CREATE_USER_ID         VARCHAR(32)  NOT NULL,
    MODIFY_DATE_TIME       TIMESTAMP,
    MODIFY_USER_ID         VARCHAR(32)
);

CREATE UNIQUE INDEX LOCAL_DELIVERY_UNIT_IDX1 ON LOCAL_DELIVERY_UNIT(CODE);

COMMENT ON TABLE LOCAL_DELIVERY_UNIT                         IS 'Holds information about a Local Delivery Unit';
COMMENT ON COLUMN LOCAL_DELIVERY_UNIT.LOCAL_DELIVERY_UNIT_ID IS 'Surrogate key';
COMMENT ON COLUMN LOCAL_DELIVERY_UNIT.CODE                   IS 'Local Delivery Unit Code. Business key';
